name: Crawl & Save

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # KST 09:00

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Resolve domains
        run: python tools/resolve_domains.py

      - name: Generate brands.yaml
        run: python tools/generate_brands_yaml.py

      - name: Run scraper
        run: python scraper/scrape.py

      # ✅ push 전에 원격 최신(main) 반영
      - name: Prepare repo (pull latest)
        run: |
          git config user.name "fitground-bot"
          git config user.email "bot@users.noreply.github.com"
          git pull --rebase origin main || true

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(data): auto resolve & crawl $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
