name: Crawl & Save

on:
  workflow_dispatch:        # 수동 실행
  schedule:
    - cron: "0 0 * * *"     # 매일 00:00 UTC (KST 09:00)

permissions:
  contents: write           # 푸시하려면 write 권한 필요

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
          pip install pyyaml beautifulsoup4 lxml requests

      - name: Resolve official domains
        run: |
          python tools/resolve_domains.py

      - name: Generate brands.yaml
        run: |
          python tools/generate_brands_yaml.py
          echo "---- brands.yaml ----"
          cat brands.yaml

      - name: Run scraper
        run: |
          python scraper/scrape.py

      - name: Pull latest changes
        run: |
          git config pull.rebase false
          git pull origin main || true

      - name: Commit & push if changed
        run: |
          git config user.name "fitground-bot"
          git config user.email "bot@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(data): auto resolve & crawl $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
